### PR TITLE
Multi guards

### PR DESCRIPTION
**Pull request by Vendin**

### CODE REVIEW

**Comment by Vendin** [comment]
`Scrutinizer` is broken

**Comment by MarceauKa** [comment]
Nice work but this notion of absolute admin (with a new migration table) don't seem appropriate to me.

**Comment by vvendin** [comment]
These are just tests, we can make tests with a second guard using a table of users

**Comment by Vendin** [comment]
These are just tests, we can make tests with a second guard using a table of users.

**Comment by Vendin** [comment]
I can remake, do not like the second table?

**Comment by Vendin** [comment]
`Scrutinizer` does not work correctly.

**Comment by Vendin** [comment]
@MarceauKa lot of time has passed. My production looks at fork half a year already. Let's solve the problems of multi guards. Give feedback, I'm ready to make edits.

**Comment by MarceauKa** [comment]
I don't want to have a database (and migrations) to manage multiple guard. It can be implemented without it.

**Comment by Vendin** [comment]
@MarceauKa I did as you wanted. Multiple guards uses one table.

**Comment by MarceauKa** [comment]
Thank you, let me review this and I'll merge! 😊

**Comment by ctf0** [comment]
@MarceauKa can u plz add the usage for this to the docs ?

**Pull request merged**
