### PR TITLE
I needed to impersonate users from multiple guards, This is first imp…

### PR DESCRIPTION
**Pull request by nenads**
…lementation

start idea was from https://github.com/404labfr/laravel-impersonate/pull/44

### CODE REVIEW

**Comment by nenads** [comment]
My main concern atm is that i have changed controller middleware from auth to web.

note:
By default, Laravel ships with two guards. web & api guards. If you use auth middleware & you don’t define what guards should be used, Laravel by default takes the web guard.

**Comment by MarceauKa** [comment]
Hi! Thank you for your contribution!
Like #44 we need tests.

**Comment by nenads** [comment]
i'm testing it on my project. But as we know who build stuff should not test :)

**Comment by MarceauKa** [comment]
You must update actual tests adding new scenarios that show inter-guards impersonation.

**Comment by nenads** [comment]
Yes, but my question was about Lab404\Impersonate\Controllers\ImpersonateController what middleware should be used ?

**Comment by nenads** [comment]
You can ignore this pull request atm.

1. Controler middleware->(auth) (fixed on my Fork) When you are imperesiting would not let you pass. Using web middleware seems not secure.
2. Write tests.

As soon as i have time i will write tests.

I can confirm that this is working as expected on my project. 
I would not trust it too without tests. For now you can see that it is backword compatible since all old tests are passing.

**Pull request closed without merging**
