### PR TITLE
Add @canBeImpersonated blade directive

### PR DESCRIPTION
**Pull request by Konafets**
This is related to #12. 

I want add tests but the testsuite is failing with the message:

```shell
18) Lab404\Tests\BladeDirectivesTest::it_not_displays_impersonating_content_directive
Symfony\Component\Console\Exception\LogicException: An option named "path" already exists.

/Users/sok/Development/laravel-impersonate/vendor/symfony/console/Input/InputDefinition.php:244
/Users/sok/Development/laravel-impersonate/vendor/symfony/console/Command/Command.php:409
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Console/Command.php:153
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Console/Command.php:111
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/ResetCommand.php:42
/Users/sok/Development/laravel-impersonate/vendor/orchestra/database/ConsoleServiceProvider.php:80
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Container/Container.php:716
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Container/Container.php:598
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Container/Container.php:567
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:708
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Console/Application.php:192
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Console/Application.php:206
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:232
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Console/Application.php:111
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Console/Application.php:58
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:287
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:221
/Users/sok/Development/laravel-impersonate/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithConsole.php:18
/Users/sok/Development/laravel-impersonate/tests/TestCase.php:19
/Users/sok/Development/laravel-impersonate/tests/BladeDirectivesTest.php:21
```

### CODE REVIEW

**Comment by MarceauKa** [comment]
Hi! Thank you for your PR.
Please add missing doc related to the new blade directive to the readme :)

**Comment by MarceauKa** [comment]
Done! Thank you again!
See the new release 1.0.11 and 1.1.0

**Comment by Konafets** [comment]
Thanks for merging. I would like to add some tests but as stated above I got the errors. Do you have any idea why?

**Comment by MarceauKa** [comment]
Don't know why but I've added some tests 👍 (See: `tests/BladeDirectivesTest.php`)

**Pull request merged**
