### PR TITLE
Implement possibility to impersonate users from other guards

### PR DESCRIPTION
**Pull request by nikolvs**
I wanted to make it possible to a user to impersonate users from other guards, so I implemented this.

Btw, thanks for the nice package. It's helping me a lot!

### CODE REVIEW

**Comment by MarceauKa** [comment]
Hi! Thank you for contributing. Please add tests :)

**Comment by nenads** [comment]
What i status of this ? Will to to go to main repo

**Comment by nenads** [comment]
> This pull request works for impersonating into any guard, but it fails when trying to use a different users provider model.
> 
> An easy fix may be implemented on the findUserById method, that method currently searches the users provider model class on the predefined auth.providers.users.model parameter in the config file.
> 
> It can be modified in order to accomodate any provider by updating how the the model is retrieved.
> 
> ```
> public function findUserById($id)
>     {
>         $provider = $this->app['config']->get('auth.guards.'.$this->getImpersonatorGuardName().'.provider');
>         $model = $this->app['config']->get('auth.providers.'.$provider.'.model');
> ...
> ```
> Here : https://github.com/alberto1el/laravel-impersonate/blob/4f3b658572a63910f5664248e4c2927b15578eef/src/Services/ImpersonateManager.php#L31

Hi does this affects my PR ?

**Comment by gizburdt** [comment]
Would be awesome if this could be implemented :)

**Comment by MarceauKa** [comment]
See the [1.4](https://github.com/404labfr/laravel-impersonate/releases/tag/1.4.0)

**Pull request closed without merging**
