### PR TITLE
This could be easily manage database test

### PR DESCRIPTION
**Pull request by lloricode**
Signed-off-by: Lloric Mayuga Garcia <lloricode@gmail.com>

### CODE REVIEW

**Comment by MarceauKa** [comment]
What the point here?

**Comment by lloricode** [comment]
the migration file is uses only for test level environment, and this should belong to a test folder. 
And also make it easy to call migration from a test class, and easily include it on gitattribute

conclusion here is all test file is much better inside test folder,

**Comment by lloricode** [comment]
remember, this library not uses migration publish

**Comment by lloricode** [comment]
maintainer did not response

**Pull request closed without merging**
