### PR TITLE
Implement multiple guards by @nikolvs @nenads backwards compatible

### PR DESCRIPTION
**Pull request by alberto1el**
This is the same as: https://github.com/404labfr/laravel-impersonate/pull/44 
With the addition of multiple users providers.
Main credit to @nikolvs & @nenads

### CODE REVIEW

**Comment by alberto1el** [comment]
Greetings, fixed the manager to handle multiauth support, this has the same API as the current master and all tests pass
@MarceauKa

**Comment by Vendin** [comment]
This PR is very similar to my PR #58, which I did before you

**Comment by alberto1el** [comment]
> This PR is very similar to my PR #58, which I did before you

Oh yes I did see that, I actually based it on @nikolsv then saw @nenads  and yours lastly, I am not trying to get credit for anything I just tried to unify all of them, improve them if possible and also add tests.

I believe this is a sum of all efforts and it is backwards compatible as you can see, I'm just trying to help.

**Comment by Vendin** [comment]
I understand you.
Your PR is flawed because the user leaves the current gard.
My PR is flawed because the the user remains in the current guard (I need this for a project in which I successfully use my fork).
The ideal solution is to specify in the configuration file whether you want to stay in the current guard or not.
But these are thoughts on the future development of the library.

**Comment by alberto1el** [comment]
> The ideal solution is to specify in the configuration file whether you want to stay in the current guard or not.
That could go on the model, something like `can_impersonate_into_guard` and maybe have an array of guards into which the current user can take impersonation.

**Comment by MarceauKa** [comment]
Looking for all of that. Thank you for your work.

**Comment by nenads** [comment]
@alberto1el what have you find that is missing in my pr. just wand to push this to main if possible.

**Comment by alberto1el** [comment]
@nenads I will take a look this weekend

**Comment by MarceauKa** [comment]
See the [1.4](https://github.com/404labfr/laravel-impersonate/releases/tag/1.4.0)

**Pull request closed without merging**
