### PR TITLE
Support for php 8.4

### LINKED ISSUE #209: PHP 8.4 support
Hi!

Here is few deprecation messages. 

```
Deprecated: can_impersonate(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead

Deprecated: can_be_impersonated(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead

Deprecated: is_impersonating(): Implicitly marking parameter $guard as nullable is deprecated, the explicit nullable type must be used instead
```

Needs little changes:

```
function can_impersonate(string $guard = null): bool 
// =>
function can_impersonate(?string $guard = null): bool
```

### PR DESCRIPTION
**Pull request by MarioGattolla**
Hi this pull request close #209 

Tell me if something wrong

### CODE REVIEW

**Comment by MarceauKa** [comment]
@MarioGattolla I'm looking for why tests are not running

**Comment by aglipanci** [comment]
@MarceauKa based on the error logs itr seems like you need to enable external actions on your repository settings at Repository Settings → Actions → General.
Screenshot 2024-12-09 at 16 46 50

**Comment by calebdw** [comment]
@MarceauKa, can we try to merge this? We're updating to PHP8.4 and these deprecation warnings are messing up our json endpoints

**Comment by sebastiansulinski** [comment]
Any indication on when will this be merged please?

**Comment by aglipanci** [comment]
@MarceauKa can you please release a new version so we can use this?

**Comment by MarceauKa** [comment]
@aglipanci Yep, I'm reviewing #207 and I'll release it

**Comment by aglipanci** [comment]
Thank you! It's appreciated that you are taking the time for this :)

**Comment by it-can** [comment]
@MarceauKa can you just do a quick release/tag so we can run php8.4 :-)

**Pull request merged**
